# Generated by Django 3.2 on 2021-07-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymentmethod',
            new_name='paymentMethod',
        ),
    ]
