# Generated by Django 3.2 on 2021-07-31 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_review_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='createdAt',
        ),
    ]
